/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Guice_two;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.guice.services.textEditar;
import com.guice.tasks.AppModule;

public class App {
  

    public static void main(String[] args) {
        Injector injector = Guice.createInjector(new AppModule());
        
        textEditar editer = injector.getInstance(textEditar.class);
        //because of another sub class binding we 
        editer.makeSpellCheck();
    	
    	
    }
}
