/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Guice_one;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.guice.request.drawRequest;
import com.guice.service.drawShap;
import com.guice.service.drawSqure;

public class App {
   

	
    public static void main(String[] args) {

//			drawShap d = new drawSqure();
    	//injector in drawShap
    	Injector injector = Guice.createInjector(new AppModle());
//			drawShap d = injector.getInstance(drawShap.class);
//			drawRequest request = new drawRequest(d);
    	
    	//injector in drawRequesti
//			--> we have to add annotation in drawRequest class above the constructor
    	drawRequest request = injector.getInstance(drawRequest.class);
    	request.makeRequest();
    	drawRequest request1 = injector.getInstance(drawRequest.class);
    	request1.makeRequest();
    	
    	
    	//here we can see that both request methods are not same for getting equal values we can use Singleton scope
    	
    	System.out.println(request.getID());
    	System.out.println(request1.getID());
    	
    	
    	boolean isSame = request.getShap() == request1.getShap();
    	System.out.println(isSame);
    	
       
    }


}
